# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de5628a9dd2818c4351631656575036caa5c40ae836ab9a1195ed93db66ef93e3036bd94aa3bff08740fc5c8fa6ecf02456c5d299ce38ad8b8cd0ac3270fc632

test:
  secret_key_base: cbf9ac5d69c741295a3723e59d60df07ecafae83a4939206185e0f0e91e19de3a7ff5e59e357582e9a05c30b66fe270c9c4d0dfc915cd934d6d3dd6fc240f5cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
